### ISSUE TITLE
Error when using SpreadsheetShiftRows(spreadsheet, start, rows)

### ISSUE THREAD

**Issue by Leigh-** [teamcfadvance/cfspreadsheet-railo#23]
**Bug/Request**
Attempting to shift a single row may cause an error. Due to missing validation, the "rows" value is being treated as an "end" row instead of an offset. 

**Code**
    <cfset sheet = SpreadsheetNew() /> 
    <cfset SpreadSheetAddColumn(sheet, "a,b,c,d,e,f") />
    <cfset SpreadSheetShiftRows(sheet, 6, 1) />

**Stack Trace**
    ... "firstMovedIndex, lastMovedIndex out of order
    at org.apache.poi.hssf.record.formula.FormulaShifter.<init>(FormulaShifter.java:39):39
    at org.apache.poi.hssf.record.formula.FormulaShifter.createForRowShift(FormulaShifter.java:48):48
    at org.apache.poi.hssf.usermodel.HSSFSheet.shiftRows(HSSFSheet.java:1325):1325
    at org.apache.poi.hssf.usermodel.HSSFSheet.shiftRows(HSSFSheet.java:1211):1211

**Comment by snow123456** [comment]
这个bug解决了么？如何解决的？
